### PR TITLE
Add tag to rooms to disable fuzzy room logic

### PR DESCRIPTION
**Pull request by Hazado**
Allows rooms that have nearly identical room descriptions to only be matched if its completely identical.

Would allow us to map crafting rooms that are all nearly the same save for a different color door, etc.

### CODE REVIEW

**Comment by rcuhljr** [comment]
Shouldn't nofuzzy be a boolean not an array?

**Comment by Hazado** [comment]
Can change it to FalseClass.new, functionally it doesn't change.

**Comment by rcuhljr** [comment]
Mind tossing in a version number bump (minor probably) and I'll merge this.

**Comment by rcuhljr** [comment]
Overcome by events.

**Pull request closed without merging**
